[package]
name = "d3d11"
version = "0.0.0"
edition = "2021"

[dependencies]
d3d11-sys = { path = "./d3d11-sys" }

bitflags = "2.6.0"
bon = "3.3.1"
paste = "1.0.15"
static_assertions = "1.1.0"
thiserror = "2.0"

[dev-dependencies]
anyhow = "1"
glfw = "0.59.0"
